ENVIRONMENT:
  MAX_EPISODE_STEPS: 200
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  SENSORS: ["DEPTH_SENSOR"]
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['SPECTROGRAM_SENSOR' , 'AngleSensor']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION' , 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
    
COLLECT:
  OPEN: False
  GRID_SIZE: 1.0
  # TYPE: "offlineversion3"
  TYPE: "greedy"
  DATA_STRUCT: {"obs":[],"reward":[],"done":[],"action_id":[],"info":[],"map":[],"path_point":[],"sound_id":[] , "greedy_action":[] , "total_sound_point":[]}
  DATA_DIR: "dataset-data3/dataset/pickle/offline(greedy)" #"pickle/greedy"
  IMG_DIR: ""
  IMG_TYPE: ""
  COLLECT_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"

TRAIN:
  OPEN: False
  SAVE_LOADER: False
  TYPE: "OfflineRL" # HybirdNetwork OfflineRL
  # TYPE: "HybirdNetwork"
  EXPERIMENT_LOSS_DIR: "PR/heard/loss"
  EXPERIMENT_CKPT_DIR: "PR/heard/ckpt"
  # TRAIN_DATASET: "dataset/lmdb/v2/greedy(angle_train)"
  # VAL_DATASET: "dataset/lmdb/v2/greedy(angle_val)"
  EPOCH: 100
  BATCH_SIZE: 128
  train_shard_pattern: ["/hdd-data3/hybird/hybird(heard_train_multiple)/foundation_model_shard_0.pt"]
  val_shard_pattern: ["/hdd-data3/hybird/hybird(val_multiple_heard)/foundation_model_shard_0.pt"]
  OFFLINE: 
    TYPE: "OfflineRL"
    buffer : False
    replay_epoch : 1000 # 首先不进行replay buffer
    model: "v1_3"
    SAVE_LOADER: False
    LOAD_PATH: False
    MODEL_PATH: 'experiment/ckpt/offline/Foundation_model_150.pth'
    EXPERIMENT_LOSS_DIR: "final/telephone/loss/8"
    EXPERIMENT_CKPT_DIR: "final/telephone/ckpt/8"
    # train_shard_pattern: "./dataset/offline/pt/v7/train_buffer.json"
    # train_shard_pattern: "./dataset/offline/pt/v5/train_greedy.json"
    train_shard_pattern: "dataset-data3/dataset/offline/pt/v10/train.json"
    train_lmdb_path: "media/lmdb/offline_with_hybrid"
    ONLINE_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"
    state_dim: 256
    action_dim: 4
    hidden_dim: 128
    # lr: 0.00004
    lr : 0.00005
    target_entropy: -4
    tau: 0.005
    beta: 0.001
    gamma: 0.99
    batch_size: 128
    num_epochs : 300
    online_test_epoch : 1
    list: "10个epoch平滑，beta0.01 , 用全部的val数据去测试"

LMDB:
  OPEN: True
  TYPE: "OfflineTwoFrameWithHybridLMDB"
  CHUNK_SIZE: 512
  # RAW_DATA_PATH: "configs/level/greedy/distance_70.pkl"
  RAW_DATA_PATH: "dataset-data3/dataset/pickle/offline(greedy)"
  TO_PATH: "media/lmdb/offline_with_hybrid"
  CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"


DATASET:
  TYPE: "AudioNav"
  SPLIT: "val_multiple"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
