ENVIRONMENT:
  MAX_EPISODE_STEPS: 200
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  SENSORS: ["DEPTH_SENSOR"]
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['SPECTROGRAM_SENSOR' , 'AngleSensor']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION' , 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
    
COLLECT:
  OPEN: False
  GRID_SIZE: 1.0
  # TYPE: "offlineversion3"
  TYPE: "greedy"
  DATA_STRUCT: {"obs":[],"reward":[],"done":[],"action_id":[],"info":[],"map":[],"path_point":[],"sound_id":[] , "greedy_action":[] , "total_sound_point":[]}
  DATA_DIR: "dataset-data3/dataset/pickle/online_val(val)" #"pickle/greedy"
  IMG_DIR: ""
  IMG_TYPE: ""
  COLLECT_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"

TRAIN:
  OPEN: True
  SAVE_LOADER: False
  TYPE: "OfflineRL" # HybirdNetwork OfflineRL
  # TYPE: "HybirdNetworkAudio"
  EXPERIMENT_LOSS_DIR: "heard_and_heard/loss"
  EXPERIMENT_CKPT_DIR: "heard_and_heard/ckpt"
  # TRAIN_DATASET: "dataset/lmdb/v2/greedy(angle_train)"
  # VAL_DATASET: "dataset/lmdb/v2/greedy(angle_val)"
  EPOCH: 100
  BATCH_SIZE: 128
  train_shard_pattern: ["dataset/hybird/hybird(heard_train_multiple)/foundation_model_shard_*.pt"]
  val_shard_pattern: ["dataset/hybird/hybird(val_multiple_heard)/foundation_model_shard_*.pt"]
  OFFLINE: 
    TYPE: "OfflineRL"
    model: "v2"
    SAVE_LOADER: False
    LOAD_PATH: False
    MODEL_PATH: 'experiment/ckpt/offline/Foundation_model_150.pth'
    EXPERIMENT_LOSS_DIR: "offlineRL/loss/v5model/22"
    EXPERIMENT_CKPT_DIR: "offlineRL/ckpt/v5model/2"
    train_shard_pattern: "./dataset/offline/pt/v7/train.json"
    ONLINE_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"
    state_dim: 256
    action_dim: 4
    hidden_dim: 128
    lr: 0.00004
    target_entropy: -4
    tau: 0.005
    beta: 0.2
    gamma: 0.99
    batch_size: 1024
    num_epochs : 300
    online_test_epoch : 10

LMDB:
  OPEN: False
  TYPE: "offlinetwoframe"
  # RAW_DATA_PATH: "configs/level/greedy/distance_70.pkl"
  RAW_DATA_PATH: "dataset/pickle/v2/greedy(hybirdnetwork_with_RGBD_train)"
  TO_PATH: "dataset/offline/pt/v7/two_frame_greedy/offline"
  CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"


DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
