ENVIRONMENT:
  MAX_EPISODE_STEPS: 100
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  SENSORS: ["DEPTH_SENSOR"]
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['SPECTROGRAM_SENSOR' , 'AngleSensor']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION' , 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
    
COLLECT:
  OPEN: False
  TYPE: "offlineLevel"
  DATA_STRUCT: {"obs":[],"reward":[],"done":[],"action_id":[],"info":[],"map":[],"path_point":[],"sound_id":[] , "greedy_action":[]}
  DATA_DIR: "dataset/pickle/v2/offline(level)" #"pickle/greedy"
  IMG_DIR: ""
  IMG_TYPE: ""
  COLLECT_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"

TRAIN:
  OPEN: True
  SAVE_LOADER: False
  TYPE: "OfflineRL" # HybirdNetwork OfflineRL
  EXPERIMENT_LOSS_DIR: "compare/loss/hybirdnetwork_RGBD_two_frame"
  EXPERIMENT_CKPT_DIR: "compare/ckpt/hybirdnetwork_RGBD_two_frame"
  # TRAIN_DATASET: "dataset/lmdb/v2/greedy(angle_train)"
  # VAL_DATASET: "dataset/lmdb/v2/greedy(angle_val)"
  EPOCH: 100
  BATCH_SIZE: 128
  train_shard_pattern: ["dataset/hybird/pt/v1/two_frame(train)/foundation_model_shard_*.pt" , "dataset/hybird/pt/v1/two_frame(collided)/foundation_model_shard_*.pt"]
  val_shard_pattern: ["dataset/hybird/pt/v1/two_frame(val)/foundation_model_shard_*.pt"]
  OFFLINE: 
    TYPE: "OfflineRL"
    model: "v4"
    SAVE_LOADER: False
    LOAD_PATH: False
    MODEL_PATH: 'experiment/ckpt/offline/Foundation_model_150.pth'
    EXPERIMENT_LOSS_DIR: "offlineRL/loss/v4model/level/test"
    EXPERIMENT_CKPT_DIR: "offlineRL/ckpt/v4model/level"
    train_shard_pattern: ["dataset/offline/pt/v3/level(level1)/offline_rl_lstm_shard_0.pt","dataset/offline/pt/v3/level(level2)/offline_rl_lstm_shard_0.pt", "dataset/offline/pt/v3/level(level3)/offline_rl_lstm_shard_0.pt" , "dataset/offline/pt/v3/level(level4)/offline_rl_lstm_shard_0.pt" , "dataset/offline/pt/v3/level(level5)/offline_rl_lstm_shard_0.pt"]
    # ONLINE_CKPT: "experiment/ckpt/hybirdnetworkRGBDCollided100k_1_lr/model_epoch_100.pth"
   
    ONLINE_CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"
    state_dim: 256
    action_dim: 4
    hidden_dim: 128
    lr: 0.0004
    target_entropy: -4
    tau: 0.005
    beta: 0.2
    gamma: 0.99
    batch_size: 64
    num_epochs : 500

LMDB:
  OPEN: False
  TYPE: "offlinelstm"
  RAW_DATA_PATH: "dataset/pickle/v2/offline(level)/level1"
  TO_PATH: "dataset/offline/pt/v3/level(level1_test)"
  CKPT: "compare/ckpt/hybirdnetwork_RGBD_two_frame/model_epoch_100.pth"


DATASET:
  TYPE: "AudioNav"
  SPLIT: "val_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}_select.json.gz"
